# Generated by Django 5.0 on 2023-12-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='mrp',
            field=models.FloatField(max_length=255),
        ),
    ]
