# Generated by Django 5.0 on 2023-12-27 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_purchase_order_mrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Address', models.CharField(max_length=255)),
                ('City', models.IntegerField()),
                ('Pincode', models.FloatField(max_length=255)),
                ('Customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.customer')),
                ('Purchase_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.purchase_order')),
            ],
            options={
                'db_table': 'Shipment',
            },
        ),
    ]
