# Generated by Django 5.0 on 2023-12-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_shipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='City',
            field=models.CharField(max_length=255),
        ),
    ]
