# Generated by Django 5.0 on 2023-12-27 08:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_shipment_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase_order',
            name='Customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='api.customer'),
        ),
    ]
