# Generated by Django 5.0 on 2023-12-27 08:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_purchase_order_customer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='Purchase_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to='api.purchase_order'),
        ),
    ]
